package com.example.slicerush;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import java.util.*;

public class MainActivity extends Activity{ public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);setContentView(new GameView(this));}
static class GameView extends View{
 Paint p=new Paint(1); Random r=new Random(); ArrayList<Item> items=new ArrayList<>(); ArrayList<Splash> splashes=new ArrayList<>(); ArrayList<PointF> trail=new ArrayList<>(); long last=System.nanoTime(),spawn=0,start=System.currentTimeMillis(); int score=0,lives=3,combo=0; boolean over=false,started=false;
 GameView(android.content.Context c){super(c);p.setTypeface(Typeface.create(Typeface.SANS_SERIF,Typeface.BOLD));setFocusable(true);} 
 protected void onDraw(Canvas c){long now=System.nanoTime();float dt=Math.min(.033f,(now-last)/1e9f);last=now; if(started&&!over)step(dt); drawBg(c); for(Item it:items)it.draw(c,p); for(Splash s:splashes)s.draw(c,p); drawTrail(c); drawHud(c); invalidate();}
 void step(float dt){spawn+=dt; float interval=Math.max(.35f,1.05f-score*.006f); if(spawn>interval){spawn=0; int n=1+r.nextInt(score>40?4:3); for(int i=0;i<n;i++)addItem();} for(int i=items.size()-1;i>=0;i--){Item it=items.get(i); it.x+=it.vx*dt; it.y+=it.vy*dt; it.vy+=980*dt; it.rot+=it.spin*dt; if(it.y>getHeight()+120){if(!it.bomb&&!it.cut)lives--;items.remove(i); if(lives<=0)over=true;}} for(int i=splashes.size()-1;i>=0;i--){splashes.get(i).life-=dt;if(splashes.get(i).life<=0)splashes.remove(i);} }
 void addItem(){float w=getWidth(),h=getHeight(); boolean bomb=r.nextFloat()<.16f; Item it=new Item(); it.bomb=bomb; it.type=r.nextInt(5); it.x=80+r.nextFloat()*(w-160); it.y=h+80; it.vx=-220+r.nextFloat()*440; it.vy=-(980+r.nextFloat()*420+score*3); it.rad=bomb?42:46+r.nextFloat()*18; it.spin=-4+r.nextFloat()*8; items.add(it);} 
 boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()==0&&!started){started=true; start=System.currentTimeMillis(); return true;} if(e.getAction()==0&&over){score=0;lives=3;items.clear();splashes.clear();trail.clear();over=false;started=true;start=System.currentTimeMillis();return true;} if(!started||over)return true; if(e.getAction()==2||e.getAction()==0){PointF q=new PointF(e.getX(),e.getY()); if(trail.size()>0){PointF a=trail.get(trail.size()-1); slice(a,q);} trail.add(q); while(trail.size()>12)trail.remove(0);} if(e.getAction()==1){trail.clear();combo=0;} return true;}
 void slice(PointF a,PointF b){int hits=0; for(int i=items.size()-1;i>=0;i--){Item it=items.get(i); if(distSeg(it.x,it.y,a.x,a.y,b.x,b.y)<it.rad&&!it.cut){it.cut=true; splashes.add(new Splash(it.x,it.y,it.color(),it.bomb)); items.remove(i); if(it.bomb){lives=0;over=true;} else {hits++; score+=1+combo/3;}}} if(hits>0)combo+=hits;}
 float distSeg(float px,float py,float x1,float y1,float x2,float y2){float dx=x2-x1,dy=y2-y1,l=dx*dx+dy*dy; if(l==0)return (float)Math.hypot(px-x1,py-y1); float t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/l)); return (float)Math.hypot(px-(x1+t*dx),py-(y1+t*dy));}
 void drawBg(Canvas c){Paint g=p; LinearGradient lg=new LinearGradient(0,0,0,getHeight(),0xff111827,0xff1e293b,Shader.TileMode.CLAMP); g.setShader(lg); c.drawRect(0,0,getWidth(),getHeight(),g); g.setShader(null); g.setColor(0x22ffffff); for(int i=0;i<9;i++)c.drawCircle((i*137)%Math.max(1,getWidth()),80+(i*211)%Math.max(1,getHeight()),2+i%4,g);}
 void drawHud(Canvas c){p.setShader(null);p.setTextAlign(Paint.Align.LEFT);p.setTextSize(52);p.setColor(0xffffffff);c.drawText("Score " + score,32,70,p);p.setTextAlign(Paint.Align.RIGHT);p.setColor(0xffff5a5f);c.drawText("❤ "+lives,getWidth()-32,70,p);p.setTextAlign(Paint.Align.CENTER); if(!started){p.setTextSize(60);p.setColor(0xffffffff);c.drawText("SLICE RUSH",getWidth()/2,getHeight()/2-40,p);p.setTextSize(32);p.setColor(0xffd1d5db);c.drawText("滑动切开水果，避开炸弹",getWidth()/2,getHeight()/2+20,p);c.drawText("点击开始",getWidth()/2,getHeight()/2+70,p);} if(over){p.setTextSize(58);p.setColor(0xffffffff);c.drawText("游戏结束",getWidth()/2,getHeight()/2-35,p);p.setTextSize(34);p.setColor(0xffffcc33);c.drawText("最终得分："+score,getWidth()/2,getHeight()/2+20,p);p.setColor(0xffd1d5db);c.drawText("点击重新开始",getWidth()/2,getHeight()/2+72,p);}}
 void drawTrail(Canvas c){if(trail.size()<2)return; p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(13);p.setStrokeCap(Paint.Cap.ROUND);p.setColor(0xccffffff);Path path=new Path();path.moveTo(trail.get(0).x,trail.get(0).y);for(PointF q:trail)path.lineTo(q.x,q.y);c.drawPath(path,p);p.setStyle(Paint.Style.FILL);} }
 static class Item{float x,y,vx,vy,rad,rot,spin;int type;boolean bomb,cut; int color(){int[] cs={0xffef4444,0xffffcc33,0xff22c55e,0xffff7a18,0xffa855f7};return cs[type%cs.length];} void draw(Canvas c,Paint p){c.save();c.translate(x,y);c.rotate(rot*57); if(bomb){p.setColor(0xff111111);c.drawCircle(0,0,rad,p);p.setColor(0xff6b7280);c.drawCircle(-12,-16,8,p);p.setColor(0xffffcc33);p.setStrokeWidth(5);p.setStyle(Paint.Style.STROKE);c.drawArc(-8-rad,-rad-30,rad+20,rad-6,210,80,false,p);p.setStyle(Paint.Style.FILL);} else {p.setColor(color());c.drawOval(-rad,-rad*.82f,rad,rad*.82f,p);p.setColor(0x55ffffff);c.drawCircle(-rad*.28f,-rad*.22f,rad*.22f,p);p.setColor(0xff166534);c.drawOval(rad*.06f,-rad*1.18f,rad*.65f,-rad*.72f,p);p.setColor(0x66000000);c.drawArc(-rad,-rad*.82f,rad,rad*.82f,20,120,true,p);} c.restore();}}
 static class Splash{float x,y,life=.45f;int col;boolean bomb;Random r=new Random();Splash(float X,float Y,int C,boolean B){x=X;y=Y;col=C;bomb=B;}void draw(Canvas c,Paint p){p.setColor(bomb?0xffff4444:col);for(int i=0;i<10;i++){float a=i*.63f,rr=(.5f-life)*260+i*3;c.drawCircle(x+(float)Math.cos(a)*rr,y+(float)Math.sin(a)*rr,8+life*12,p);}}}
}
